### ISSUE TITLE
indent motion in insert mode

### ISSUE THREAD

**Issue by twmht** [tmhedberg/indent-motion#2]
hi,
I am writing python script

```
def outside():
    a = 5
    def inside():
        print x
```

If I am on `a=5`, I want to insert the return-statement in the level of outside()
This is the result I want

```
def outside():
    a = 5
    def inside():
        print x
    return a
```

I can do this by typing `<Leader>]` on line `a=5` in the normal mode
and I can jump to line `print x` of the level of the inside().
After this, I can type `o` to go to the insert mode but still in the level of the inside().
And I have to backspace one tab to produce the result I want.
This is annoying when the body of outside() function is out of the vim page and has many nested levels in the last part, so that I have to do many backspace.

Any comments?

Thank you

**Comment by tmhedberg** [comment]
I can see how that might be annoying, but it doesn't have anything to do with this plugin. You would see the same behavior if you moved to the `print x` line by any other means and pressed `o` to start a new line below it.

If you have the `autoindent` option set, then when you press `o`, Vim copies the indentation of the previous line onto the new line. That's not what you want in this case, but how could Vim know that? Maybe you wanted to continue the definition of the `inside` function rather than de-indenting to add a new statement to `outside`. It can't read your mind to determine your intent.

**Comment by twmht** [comment]
hi,
I know that this is the behavior of `autoindent` rather than this plugin.

Is it possible to have the same indent-level of `a=5` if I type some quick commands like `,]` and automatically to go to the insert mode?

for example,

``````
def outside():
    a = 5
    def inside():
        print x
    | #this is the current cursor with the same indent-level of ```a=5``` and I am in the insert mode after I type some quick commands  in line ```a=5```
``````

I am not sure if this is possible to achieve that with vim?

Thanks for your comment

**Comment by tmhedberg** [comment]
So are you suggesting that a new key mapping be added to indent-motion that enters insert mode automatically after moving the cursor, and copies the indentation of the line you moved from?

That is certainly possible to do in Vim, and not even very difficult, but I think it falls outside of the scope of this very simple plugin. indent-motion is just about moving the cursor; what you do after that its out of its purview. If you want to implement something like that for yourself, I can probably give you some tips to get you started, but I don't think the implementation belongs in this project.

If I'm misunderstanding your suggestion, feel free to correct me.

**Comment by twmht** [comment]
Yes! This is what I am suggesting.

from

```
def outside():
    a = 5
    def inside():
        print x
```

to

``````
def outside():
    a = 5
    def inside():
        print x
    | #this is the current cursor with the same indent-level of ```a=5``` and I am in the insert mode after I type some quick commands  in line ```a=5```
``````

It should be noted that it will automatically creates a new line after `print x` and this line has the same indent-level with `a=5`
I think this feature will be very useful for me.

Thank you

**Comment by tmhedberg** [comment]
My approach would be to write a small function which calls Vim's `indent` function to get the indent level of the current line. Then you can invoke indent-motion to move the cursor, add a new line, and insert the appropriate amount of indentation at the beginning of the line. Define your mapping to call that function.

Something like this snippet would have the desired effect, assuming your mapleader is `,`:

``` VimL
let ind = indent('.')
normal ,]o
execute 'normal! ' . ind . 'a '
startinsert!
```

That's just off the cuff and may not work exactly as described, but it should set you on the right track.

**Comment by twmht** [comment]
Thank you!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
