### ISSUE TITLE
Difference with jeetsukumaran/vim-indentwise?

### ISSUE THREAD

**Issue by Asheq** [tmhedberg/indent-motion#3]
Hey, I'm looking to add some new vim motions to my arsenal, and I found this one, which is really cool!

Just wanted to see if you could comment on the difference between this plugin and the one here: https://github.com/jeetsukumaran/vim-indentwise (specifically the `[%` and `]%` motions).

Thanks!

**Comment by tmhedberg** [comment]
I'm not familiar with the other plugin, so I can't really comment from personal experience. But you're right that the `[%` and `]%` motions seem more or less equivalent to what this plugin provides. My version doesn't have the repeating feature that theirs has.

Overall, their plugin seems to have more functionality, so I'd probably recommend trying it out if you think you'd find those additional features useful.

**Comment by Asheq** [comment]
Thanks for the response. I'll try out both.
